- name: install Apache
  apt:
    name: "{{ package }}"
    state: present
    update_cache: true

# - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
#   ansible.builtin.user:
#     name: johnd
#     comment: John Doe
#     uid: 1040
#     group: admin